apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-myhost--net
spec:
  destination:
    namespace: cert-manager
    server: 'https://kubernetes.default.svc'

  sources:
  - repoURL: 'git@github.com:qdrddr/WrenAi-k8s.git'
    path: infra-deployments/external-dns/manifests/bitnami
    targetRevision: main

  - repoURL: 'registry-1.docker.io/bitnamicharts'
    path: 'external-dns'
    #helm inspect chart oci://registry-1.docker.io/bitnamicharts/external-dns
    #6.32.1
    targetRevision: 6.36.1
    chart: external-dns
    helm:
        valueFiles:
          - $values/infra-deployments/external-dns/myhost--net/bitnami-6.31.5-helm-values.yaml

  - repoURL: 'git@github.com:qdrddr/WrenAi-k8s.git'
    targetRevision: main
    ref: values

  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
